[package]
name = "identity"
version = "0.1.0"
authors = ["CPerezz <c.perezbaro@gmail.com>"]
edition = "2018"

[dependencies]
web3 = "0.5.1"
rustc-hex = "2.0.1"
ethabi = "6.1.0"
tiny-keccak = "1.4.2"
ethereum-types = "0.4.0"